[package]
name = "kifetch"
version = "0.1.0"
edition = "2021"

[dependencies]
nvml-wrapper = { version = "0.10.0" }
serde = { version = "1.0.203" }
serde_derive = { version = "1.0.203" }
serde_json = "1.0.117"
sysinfo = "0.30.12"
